### ISSUE TITLE
compiler issues

### ISSUE THREAD

**Issue by micsthepick** [VisualCodeBase/CodeBase#10]
compile is failing when using IDE:

    "C:\CodeBase\CodeBase\Bin\cb.exe" -tos=win64         "myplugin.cb -debug -s -c" 

...

    Error: File not found - 'myplugin.cb -debug -s -c'

this was on a new VST CodeBase project, and changing to VST cpp has the same issue.
and if I go back to using the usual method of compilation via batch file, I get the following additional error:

    fatal error: D:/Programming/t/RunTime/Classes/clsSCI/Inc/SciLexer.h: No such file or directory
      339 | #include "D:/Programming/t/RunTime/Classes/clsSCI/Inc/SciLexer.h"

and finally, using the following file as a drop in replacement: http://freesourcecode.net/cprojects/109969/sourcecode/SciLexer.h
and changing the include path to point to that file, I run into the following error:

    error: 'cb_GetWndData' was not declared in this scope; did you mean 'cb_GetWndDPI'?

**Comment by VisualCodeBase** [comment]
thank you very very much
this indeed a bug
will be fixed soon

at the meantime,
those lines are by mistake in wcontrols.h/wcontrols64.h.
 you can comment them if you want.
 
**********************
about  cb_GetWndData it should work well.
this macro is defined in CodeBase.h/CodeBase64.h
ensure that one of these headers included in your source.
usually the compiler include them for you.
if they are not, then it is a bug.
but than none of the projects should work.
so it's probably mistake on your side ?

**********************
this is a bug in the ide
"C:\CodeBase\CodeBase\Bin\cb.exe" -tos=win64         "myplugin.cb -debug -s -c"
will be fixed soon
thanks

**Comment by micsthepick** [comment]
thanks, and yes, that last error was simply a consequence of having the incorrect include directories in my compile script.

**Comment by micsthepick** [comment]
hmm, If I remove -fpermissive from my compile script, the following error appears:
```
 error: invalid conversion from 'unsigned int' to 'const char*' [-fpermissive]
 4040 |  return pvf_eelGFX_MakeFont((cb_UInteger)x,(cb_UInteger)Index,sze,(cb_UInteger)flags);
      |                                            ^~~~~~~~~~~~~~~~~~
      |                                            |
      |                                            unsigned int
```
and if I don't run pvf with -lang=cpp, then it generates more invalid code:
```
myplugin.cpp: In member function 'double pvf_EffectClass::filters_i_apass_do_f(double*, double*, double*, double*, double*, double*, double)':
myplugin.cpp:10829:27: error: invalid types 'double[int]' for array subscript
10829 |  tmp__v = in__v + (y1_i[0][0]-b_i[0]) + (y2_i[0][0]-a_i[0]);
```

**Comment by micsthepick** [comment]
one other thing: the pvf compiler does not pass the cflags arguments correctly, it needs to put an equals: e.g. workaround is to use -pc=-pc==-fpermissive (use of double equals)

**Comment by micsthepick** [comment]
perhaps the generated cb should actually say:
```
SUB pvf_eelGFX_MakeFontM(x, Index=-1, sze#=0, flags=0: Double) As Double : Exit = pvf_eelGFX_MakeFont((As UInt)x,(As Char*)(As UInt)Index,sze,(As UInt)flags)
```

**Comment by VisualCodeBase** [comment]
i cannot produce the bug with makefont, nor with the invalid code.
can you show the source ?

**Comment by micsthepick** [comment]
will have to double check tomorrow, and see if I can isolate where the problem is

**Comment by VisualCodeBase** [comment]
i found and fixed bug with makefont
new version with bug fixes

**Comment by micsthepick** [comment]
there are some issues with the [cookdsp ](https://github.com/belangeo/cookdsp) library. I can get rid of a few of them by just commenting out `//import cookdsp/midi.jsfx-inc`, however the following lines *had* issues  

firstly, this function only has issues when lang is not set to cpp:
cookdsp\filters.jsfx-inc:840-847
```
function apass_do(signal)
(
    in_ = signal + this.y * this.feed;
    tmp_ = in_ + (this.y1 * -this.b) + (this.y2 * -this.a);
    this.y = (tmp_ * this.a) + (this.y1 * this.b) + this.y2;
    this.y2 = this.y1; this.y1 = tmp_;
    this.y;
);
```

and secondly, the error with makefont is harder to trace the source for, but only happens when I include cookdsp.... that being said, I just saw that you fixed it then.

**Comment by VisualCodeBase** [comment]
thank you very much.
i definitely should add this lib to the tests, and reopen this issue until then.

**Comment by VisualCodeBase** [comment]
i just uploaded fixed version which handle the invalid code
i still keep this open until a test with the lib

**Comment by micsthepick** [comment]
still an issue with conversion to const char*, I will investigate further.

**Comment by micsthepick** [comment]
in the meanwhile, thanks for actively developing this project, and being so responsive! I know that things can be hard to keep up with, even without global pandemics like Covid. Keep it up!

**Comment by VisualCodeBase** [comment]
don't worry about the conversion bug, i'll find it when i test the lib
thanks for your help
edit: if the bug appear in your script then it is required.
edit: -pc== is not required, it was a bug that fixed. you should NOT use ==

**Comment by VisualCodeBase** [comment]
new version that compiles cookdsp with no problems
there was only one issue  with the library,
when writing a midi LESS plugin, there was missing declaration.

reminder: still waiting for your source to produce the conversion issue.

**Comment by micsthepick** [comment]
```
desc:minimum complete verifiable example


slider1:1<0,1,1>A
slider2:2<3,4,1>B

// inputs
in_pin:Test_in_L
in_pin:Test_in_R

// outputs
out_pin:Test_out_L
out_pin:Test_out_R


@init
toggle = slider1;

@slider
toggle = slider1;

@sample
// if Toggle is Off, set spl0 and spl1 to 0
toggle == 1 ? (spl0 = 0; spl1 = 0) : (spl0 = spl0; spl1 = spl1);

@gfx 800 0
gfx_x = 0;
gfx_y = 0;
gfx_set(1,1,1,1);
```
seems to be sufficient to trigger the error, the command I used to compile was `C:\CodeBase\CodeBase\Bin\pvf.exe options -debug`

**Comment by VisualCodeBase** [comment]
fixed.
thanks.
