### ISSUE TITLE
improved Documentation for PVF

### ISSUE THREAD

**Issue by micsthepick** [VisualCodeBase/CodeBase#12]
I would like to, e.g. change the version indicator and/or the unique plugin id, so that different plugins do not clash.

What would be helpful is a brief description of the description lines, for example, I discovered that you can provide an author:, name:, product:, and vendor: (perhaps some of these are not working), and I've tried adding a version tag, but that seems to only change the name as reported by the plugin, the actual version remains at 1.
 
I'm not sure if this is causing an issue where new plugins are not working, but for a while I have not been able to get any output through a plugin with VSTHost with VSTs compiled using the latest compilers.

**Comment by VisualCodeBase** [comment]
as i remember all those and also version are implemented.
if you still have problems please post the source.
thank you very much for your issues. it helps a lot improving the software.
edit: if you're speaking about the compilers version, it should not affect the plugins, but this also will be handled

**Comment by micsthepick** [comment]
thanks. I'll further investigate the issue of slient audio.
