### ISSUE TITLE
DAWs are detecting effects as synth

### ISSUE THREAD

**Issue by TitanGames-729** [VisualCodeBase/CodeBase#15]
Hi, i am using latest version of codebase, i managed how to compile js plugins with it and i recompiled ReEQ by REJJ, it is same as in the example but they both are detecting in fl studio as synth. For some reason, i cannot change it to effect, it is changing automatically to synth. It worked 1 time in Fl Studio but 12 and after plugin scan it changed to synth again. The plugin from example has the same issue. Also if i will close the daw or change the plugin to another then windows show that fl studio crashed, 2 times, but that not affecting the daw and it continue to work.

**Comment by VisualCodeBase** [comment]
thank you very much, will check, if something wrong with pvf or not.
for such cases that pvf auto detect plugin type is not what you want, you can force pvf to build it as you want
with command line switch:
-eff 
-syn
the first one for effect plugin
the second for synth plugin

you can add these switches to the project

**Comment by TitanGames-729** [comment]
Huge thanks! it is detecting how vst now however the plugin not processing anything except of reaper where the plugin work perfectly as vst.

![0bmlvSG3UZ](https://user-images.githubusercontent.com/65860077/204383294-d02a49de-68ff-4090-a492-2dd835d4514d.png)

P.S. Miss clicked on close issue *Face Palm*

**Comment by micsthepick** [comment]
having the same issue with a plugin detected as a vsti in reaper, and setting -eff makes it work normally.
