### ISSUE TITLE
Slider defaults

### ISSUE THREAD

**Issue by micsthepick** [VisualCodeBase/CodeBase#16]
the sliders start pointing to the right location, but double clicking on the slider to reset it puts the slider to halfway up, instead of the default value.

**Comment by micsthepick** [comment]
issue is only when there is no GFX section, and thus lice is not used

**Comment by VisualCodeBase** [comment]
thank you. will check.

**Comment by VisualCodeBase** [comment]
if there is no gfx section, how can you see auto sliders ?
are you speaking about the PVF (gui) sliders, or those by the DAW ?
can you post the effect source ?
you can empty the block/sample section

**Comment by micsthepick** [comment]
I think that I later discovered that it was reaper's default sliders, so I am unsure if they can be set to a default apart from 0.5?

**Comment by VisualCodeBase** [comment]
As far as i know there is no option in the vst sdk to tell the daw
The default value.
I might be wrong.
When i have time, i'll check.
