### ISSUE TITLE
Cannot convert 'double*' to 'double' in return 

### ISSUE THREAD

**Issue by TitanGames-729** [VisualCodeBase/CodeBase#17]
Good evening! I am trying to compile a convolution effect however i receive this error 
![AEUgDaZraq](https://user-images.githubusercontent.com/65860077/210412703-098aad8c-8309-433a-8f31-ae777303f2fe.png)
![Owq9U3TT3q](https://user-images.githubusercontent.com/65860077/210412706-cd761ecd-0471-4996-b20f-5a5b9aef92ea.png)
I have no idea what it may be. I guess what VCB is not supporting convolve_c...

**Comment by VisualCodeBase** [comment]
Thank you, it's a bug
Will be fixed.

At the mean time you can fix it your self if you like ,
By compiling it only in pvf with switch -c
Fix the source of the macro,
And then build the source with codebase.

**Comment by VisualCodeBase** [comment]
fixed
