### ISSUE TITLE
Typo in wave suport?

### ISSUE THREAD

**Issue by micsthepick** [VisualCodeBase/CodeBase#19]
I think there is an extra underscore in CodeBase\Source\Lib\PVF\Modules\File\File.cb:

it says:

    #IfDef _pvf_ReadWave_ : _

but the following effect only compiles when I change it to

    #IfDef _pvf_ReadWave : _

EFFECT:

```
desc: test plugin

slider1:/:test.wav::WAV File
@init
handle = file_open(slider1);
file_riff(handle, num_channels, samplerate);
file_close(handle);

@gfx 500 10
gfx_set(0);
gfx_rect(0, 0, gfx_w, gfx_h);

@sample
```

**Comment by micsthepick** [comment]
also of note, the plugin doesn't compile correctly without the top line: "desc: ...", because it does not include the required libraries, perhaps because it fails to recognize the included file as A JSFX.

**Comment by VisualCodeBase** [comment]
thanks
sorry for the late reply.

* the wave was fixed.

* yes the 'desc' is required for identify it as an eelfx.
you can ignore it , if you use cmdline switch -e,
and also in the @include directive with the same switch
look at yutani.pvf
