### ISSUE TITLE
scilexer and vb_def hardcoded paths in wControls[64].h

### ISSUE THREAD

**Issue by micsthepick** [VisualCodeBase/CodeBase#20]
in the included file wControls64.h and wControls.h, there are 3 instances of #include "D:/Programming/Temporary/RunTime/Classes/clsSCI/Inc/SciLexer.h", and one hardcoded path: #include "C:/Programs/Windows/CodeBase/Include/vb_Def.h"
I can fix the hardcoded path, but which version of SciLexer is needed?

**Comment by VisualCodeBase** [comment]
Thank you very much. fixed
