### ISSUE TITLE
64 bit compiler not exposed to IDE

### ISSUE THREAD

**Issue by micsthepick** [VisualCodeBase/CodeBase#4]
Either the 64 bit g++ compiler is not available from the IDE, or I'm just not able to figure out how to get it to work

**Comment by micsthepick** [comment]
If I edit pvf_FLAGS under [preset Default] (can do so by clicking on "Build" - the clicker icon) then it builds in 64 bit mode. Also, can pass -p64 to use 64 bit precision

**Comment by micsthepick** [comment]
it works if I set cb_GPP64=1 as an environment variable, and pass the following arguments: 
![image](https://user-images.githubusercontent.com/11528421/142719533-7a7dbddc-c404-4329-acd9-d50219ffe952.png)

**Comment by VisualCodeBase** [comment]
thank you very much for trying the ide and even find a work around (that i didn't think of)!!!
what i know and wrote somewhere that the ide is not ready .
the 64 bit in the current ide is not implemented yet.
 it was in a pause state because of accidently lost of source.
it is now in develop state.

**Comment by VisualCodeBase** [comment]
Implemented
