### ISSUE TITLE
pow-equals generates invalid code

### ISSUE THREAD

**Issue by micsthepick** [VisualCodeBase/CodeBase#5]
If I use JSFX code that includes such a line:

```
x ^= ex
```

it generates invalid code:

```
x(_a,) = ex_a = cb_Pow(x(_a,) = ex_a);
```

**Comment by micsthepick** [comment]
temporary workaround looks to be just converting `x ^= y` to `x = x ^ y`

**Comment by VisualCodeBase** [comment]
thank you very much! will be checked.

**Comment by VisualCodeBase** [comment]
fixed
