### ISSUE TITLE
combobox issues

### ISSUE THREAD

**Issue by micsthepick** [VisualCodeBase/CodeBase#6]
Setting the value of any combo-box except the first in a plugin GUI doesn't work properly, unless it's done with slider automation in the host side.
An interesting thing to note is that I tried to use `D=USE_WCOMBOBOX` to get it to work, and I noticed that the following lines in CodeBase/Include/wControls64.h:

```
#define wComboBox_GetWidth(x) cb_GetWndWidth((x)->hWnd,FALSE)
#define wComboBox_GetHeight(x) cb_GetWndWidth((x)->hWnd)
```

are a bit inconsistent. I managed to get it to compile with 

```
#define wComboBox_GetWidth(x) cb_GetWndWidth((x)->hWnd,FALSE)
#define wComboBox_GetHeight(x) cb_GetWndWidth((x)->hWnd,TRUE)
```

please double check those lines (the name is a little confusing too).

after compiling, the first slider shows up, but not the second, so I'm still left with only one functional combo box!

**Comment by micsthepick** [comment]
I can get it to work by modifying the .cpp file to use the following definition:

```
cb_Integer  cb_DEFCALL cb_GetWndHeight (HWND,cb_Integer=FALSE);
```

but that's still with `-D=USE_WCOMBOBOX` as a cb.exe argument

**Comment by micsthepick** [comment]
I can propose a fix for the sliders issue without `-D=USE_WCOMBOBOX`, that case needs to be done seperately:

Sliders.cb: line 132:
```
    if LOWORD(wParam) = 1 < m_ComboBoxesCnt if HIWORD(wParam) = CBN_SELCHANGE {

```
becomes
```
    if LOWORD(wParam-1) < m_ComboBoxesCnt if HIWORD(wParam) = CBN_SELCHANGE {
```

**Comment by VisualCodeBase** [comment]
sorry i didn't follow all your changes.
yesterday  i checked your first reply and found that you probably messed with wcontrols64.h
because there is no such line:
#define wComboBox_GetHeight(x) cb_GetWndWidth((x)->hWnd)
the original line is:
#define wComboBox_GetHeight(x) cb_GetWndHeight((x)->hWnd)

anyway i found an issue.
it will be fixed on the next upload.
what i suggest is that you reinstall the software
and then if you want to use wComboBox
you should edit file:
source/lib/pvf/classes/sliders/sliders.inc
and add this line (before #include line):
Macro ._foo_ = WndHeight

this will cause the compiler to emit the missing declaration

**Comment by VisualCodeBase** [comment]
> I can propose a fix for the sliders issue without `-D=USE_WCOMBOBOX`, that case needs to be done seperately:
> 
> Sliders.cb: line 132:
> 
> ```
>     if LOWORD(wParam) = 1 < m_ComboBoxesCnt if HIWORD(wParam) = CBN_SELCHANGE {
> ```
> 
> becomes
> 
> ```
>     if LOWORD(wParam-1) < m_ComboBoxesCnt if HIWORD(wParam) = CBN_SELCHANGE {
> ```

thank you very very much!

**Comment by micsthepick** [comment]
note that I also forgot to move the following line from after that modification:
```
    me = (pvfSliders*)(Sender.clsParent)
```
It is needed to get m_ComboBoxesCnt, otherwise we are dereferencing a null (or worse garbage) pointer. I've pushed a commit fixing that issue, and also including the other change to get the compiler definitions correct, so now comboboxes should work for this branch

**Comment by VisualCodeBase** [comment]
> note that I also forgot to move the following line from after that modification:
> 
> ```
>     me = (pvfSliders*)(Sender.clsParent)
> ```
> 
> It is needed to get m_ComboBoxesCnt, otherwise we are dereferencing a null (or worse garbage) pointer.

thank you very very much also for this.

**Comment by VisualCodeBase** [comment]
fixed
