### ISSUE TITLE
Dual 32 and 64 bit support

### ISSUE THREAD

**Issue by micsthepick** [VisualCodeBase/CodeBase#9]
My current workflow builds a 32 and 64 bit version for both precisions of floating point, single and double (that is 4 versions). This is so that the plugin works in various applications. I would like to recommend that the plugin compiler be changed so that it can support processReplacing and processDoubleReplacing simultaneously, by always using double processing internally, and converting the float in processReplacing to a double to process, and back to a float to output.

That way it will be similar to other plugins, that just have a 32 bit and 64 bit version, for the system architecture, and both can support either type of floating point numbers. Thoughts?

**Comment by VisualCodeBase** [comment]
it already does this.
by default it does double , and if it recognize a host that doesn't support double (like fl studio)
it does the converting

in addition it can explicitly build either single or double.
see pvf command line help.

is that what you mean ?

**Comment by micsthepick** [comment]
yes, I think the command line options had me confused.
